### ISSUE TITLE
Saved multi output cells on large notebook have never been activated

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-multi_outputs#1]
I activated Multi output cells on large notebook(about >= 100KB) and saved it to disk.
When I try to open the notebook, there are no tabs... though `Multi output` check is preserved.

It works fine with a notebook which consists of a few cells.

**Comment by yacchin1205** [comment]
It seems that the notebook is not loaded completely when the extension is loaded.

I assume that we should use `notebook_loaded.Notebook` event, like https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/nbextensions/toc2/main.js#L121-L125

I'm going to fix this 😃

**Comment by taka4ma** [comment]
Fixed
