### ISSUE TITLE
Clearing the cell outputs make the multi output tabs disappear

### ISSUE THREAD

**Issue by shingo78** [NII-cloud-operation/Jupyter-multi_outputs#11]
After clearing the outputs of multi output cell, the tabs disappear.
The outputs are not displayed, even if you re-execute the cell.

Before
![image](https://user-images.githubusercontent.com/10056150/29701387-5b870ba8-89a6-11e7-8d55-d9f93420a521.png)

After clear and re-execute
![image](https://user-images.githubusercontent.com/10056150/29701415-7ca49af8-89a6-11e7-94e1-ee532d9cdf96.png)
no outputs

**Comment by yacchin1205** [comment]
Fix by #17
