### ISSUE TITLE
The some parts of outputs are displayed in all tabs, if the cell has multi type outputs

### ISSUE THREAD

**Issue by shingo78** [NII-cloud-operation/Jupyter-multi_outputs#12]
If you make a chart with '`%matplotlib inline'` in a cell, the cell outputs 2 part data, the `execute_result` type data and the `display_data` type data.
In this case, the `execute_result` type output are displayed in the all tabs.

# Reproduction procedure
## 1st execution
![image](https://user-images.githubusercontent.com/10056150/29702548-bac18ff2-89ac-11e7-8c9f-be1bba73ae4f.png)
outputs:
1. `<matplotlib.axes._subplots.AxesSubplot at 0x7f67a121a610>`, `execute_result` type
2. the chart image, `display_data` type

## 2nd execution
![image](https://user-images.githubusercontent.com/10056150/29703097-13d93584-89af-11e7-8aff-adc34891247e.png)

2nd tab contents:
1. `<matplotlib.axes._subplots.AxesSubplot at 0x7f67a121a610>`, `execute_result` type (1st execution output)
2. `<matplotlib.axes._subplots.AxesSubplot at 0x7f67a1094cd0>`, `execute_result` type (2nd execution output)
3. the chart image, `display_data` type (2nd execution output)

## select 1st tab
![image](https://user-images.githubusercontent.com/10056150/29703276-dac4f48a-89af-11e7-86e7-4b9d46d24045.png)

1st tab contents:
1. `<matplotlib.axes._subplots.AxesSubplot at 0x7f67a121a610>`, `execute_result` type (1st execution output)
2. the chart image, `display_data` type (1nd execution output)
3. `<matplotlib.axes._subplots.AxesSubplot at 0x7f67a1094cd0>`, `execute_result` type (2nd execution output)

Even when you switch the current tab, all `execute-result` type outputs are always displayed in all tabs.

I assume that the multi_outputs extension appends only the last output to the tab area.

**Comment by yacchin1205** [comment]
Fix by #17
