### ISSUE TITLE
The outputs are splitted to tabs for each data type, after reloading the notebook

### ISSUE THREAD

**Issue by shingo78** [NII-cloud-operation/Jupyter-multi_outputs#13]
If the cell has multi type outputs, after reloading the notebook, the outputs are splitted to tabs for each data type.
 
Before reloading
![image](https://user-images.githubusercontent.com/10056150/29704087-37c51cac-89b3-11e7-81a5-b1d19aa6ca48.png)

After reloading
![image](https://user-images.githubusercontent.com/10056150/29704176-9ed6236e-89b3-11e7-9f58-8c6418a2ac80.png)

![image](https://user-images.githubusercontent.com/10056150/29704155-87aad6da-89b3-11e7-9b96-be8e487824d9.png)

**Comment by yacchin1205** [comment]
Fix by #17
