### ISSUE TITLE
The Out prompt is not displayed

### ISSUE THREAD

**Issue by shingo78** [NII-cloud-operation/Jupyter-multi_outputs#16]
When multi_outputs is disabled
![image](https://user-images.githubusercontent.com/10056150/29817268-68b5c306-8cf2-11e7-9abb-b654ed12a7f0.png)

When multi_outputs is enabled
![image](https://user-images.githubusercontent.com/10056150/29817272-6ca79a02-8cf2-11e7-8fde-6758cb368e28.png)

**Comment by yacchin1205** [comment]
Fix by #17
