### ISSUE TITLE
Attempt to access undefined object at extend_prompt function

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-multi_outputs#19]
In extend_prompt function, an exception about method invocation to undefined object occurred.
(Sorry that I could not preserve the trace of exception...)

It seems that `output_area` variable is undefined:
https://github.com/NII-cloud-operation/Jupyter-multi_outputs/blob/release/version2/main.js#L184

**Comment by shingo78** [comment]
It seems that `create.Cell` event handler does not check cell type, always calls `extend_cell`.
`extend_call` function expects that the parameter is code cell object.

https://github.com/NII-cloud-operation/Jupyter-multi_outputs/blob/4e45c04bd186524903619fa840a74ef03aa28099/lc_multi_outputs/nbextension/main.js#L56-L60

I will fix it, send PR.
