### ISSUE TITLE
Cell toolbar callback name conflicts with init_cell extension

### ISSUE THREAD

**Issue by shingo78** [NII-cloud-operation/Jupyter-multi_outputs#3]
If both `multi_outputs` and `init_cell` extensions installed and enabled, **Initialization Cell** checkbox appears instead of  **multi outputs** checkbox in cell toolbar.

I assume that the callback name conflicts with init_cell extension.

**Comment by naka999** [comment]
If you change the callback name 'init_cell.is_init_cell' to an other, it will work.

**Comment by shingo78** [comment]
fixed via d40d2204fce4500367c3bb77e8a5e7dbefde0b18
